version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - sudo apt install git
      - node --version
      - npm --version
      - echo "Installing yarn"
      - npm install -g yarn
      - echo "Installing Amplify CLI"
      - yarn global add @quasar/cli
      - echo "Installing dependencies ..."
      - cd spa
      - yarn install --ignore-engines

  build:
    environment:
      NODE_ENV: "production"
    commands:
      - echo "EsLint application ..."
      - yarn lint --fix
      - echo "Building application ..."
      - yarn build
artifacts:
  type: "zip"
  name: "build.zip"
  base-directory: "spa/dist/spa"
  files:
    - "**/*"
  discard-paths: "no"
